defaults: &defaults
    # Required.
    client_id: 126893080668338
    client_secret: 9bcd871e48fbe6b6493a4933b00e144b
    authorization_server: https://graph.facebook.com
    # requested_scope: email,offline_access,user_about_me,friends_about_me,user_activities,friends_activities,user_birthday,friends_birthday,user_education_history,friends_education_history,user_events,friends_events,user_groups,friends_groups,user_interests,friends_interests,user_likes,friends_likes,user_location,friends_location,user_notes,friends_notes,user_online_presence,friends_online_presence,user_photo_video_tags,friends_photo_video_tags,user_photos,friends_photos,user_relationships,friends_relationships,user_religion_politics,friends_religion_politics,user_status,friends_status,user_videos,friends_videos,user_website,friends_website,user_work_history,friends_work_history,read_friendlists,read_stream,publish_stream
    requested_scope: email,offline_access,user_about_me,user_activities,user_education_history,user_events,user_groups,user_interests,user_likes,user_location,user_notes,user_status,user_videos,user_website,user_work_history,read_stream,publish_stream
    authorize_path: /oauth/authorize
    access_token_path: /oauth/access_token

development:
  <<: *defaults

test: &test
  <<: *defaults

production: &production
  <<: *defaults
  client_id: 111097285601877
  client_secret: 5fe13893b5c7fca39d50c2eae5193d92

# staging:
#   <<: *production
#
# cucumber:
#   <<: *test